baseURL = "https://patasicarbon.github.io/patasicarbon-www-1/"
relativeURLs = true
uglyURLs = true
canonifyURLs = true

title = "Patasi Carbon Frame Repairs"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

author = "Peter Patasi"
description = "Carbon Frame Repairs"
keywords = "carbon frame repair smith falls ontario kingston ottawa toronto montreal eastern ontario western quebec affordable prices peter patasi"


paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Peter Patasi"
description = "Carbon Frame Repairs"
keywords = "carbon frame repair smith falls ontario kingston ottawa toronto montreal eastern ontario western quebec affordable prices peter patasi"
info = "Carbon Frame Repairs by Peter Patasi"
avatarURL = "images/avatar.jpg"
gravatar = "patasiturbo@gmail.com"
footerContent = "Patasi Carbon Frame Repairs in Smiths Falls, Ontario, Canada"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2005

# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Email"
icon = "fa fa-mail-forward"
weight = 1
url = "mailto:patasiturbo@gmail.com"
rel = "alternate"
type = "application/rss+xml"

[[params.social]]
name = "RSS"
icon = "fa fa-rss"
weight = 2
url = "https://www.peterpatasi.com/"
rel = "external"
target= "_blank"
type = "application/html"

[languages.en]
languageName = ":en:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Services"
weight = 2
url = "services/"

[[languages.en.menu.main]]
name = "Testemonials"
weight = 3
url = "testemonials/"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[languages.ca-fr]
languageName = ":french:"
title = "Patasi Carbon Bikes Repairs"

[languages.ca-fr.params]
author = "Peter Patasi"
info = "FR - Carbon Frame Repaires par Peter Patasi"
description = "FR - Carbon Frame Repairs"
keywords = "velo carbon frame repair smith falls ontario kingston ottawa toronto montreal eastern ontario western quebec affordable prices peter patasi"

footerContent = "Carbon Frame Repairs in Smiths Falls, Ontario, Canada"

[[languages.ca-fr.menu.main]]
name = "Moi"
weight = 1
url = "about/"

[[languages.ca-fr.menu.main]]
name = "Service"
weight = 2
url = "services/"

[[languages.ca-fr.menu.main]]
name = "Testemonials"
weight = 3
url = "testemonials/"

[[languages.ca-fr.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

